-- drop database if exists crackerDB;
-- create database crackerDB;

drop table if exists Users cascade;
drop table if exists Sprints cascade;
drop table if exists Projects cascade;
drop table if exists Tasks cascade;
drop table if exists Files cascade;
drop table if exists Notes cascade;
drop table if exists Logs cascade;

drop type if exists user_role;
drop type if exists task_state;

-- ENUM
create type user_role as enum (
    'Менеджер',
    'Разработчик',
    'Админ'
);

create type task_state as enum (
    'Новая',
    'Готова к работе',
    'В работе',
    'На обсуждении',
    'Ревью',
    'Выливка',
    'Проверка',
    'Проверена',
    'Релиз',
    'Выполнена',
    'Отменена',
    'Возвращена',
    'Доработка'
);

-- Таблицы
create table Users (
	id integer generated by default as identity primary key,
	name varchar(150),
	login varchar(30),
	role user_role default 'Разработчик',
	passwd varchar(150)
);

create table Sprints (
	id integer generated by default as identity primary key,
	name varchar(50),
	start_time timestamp with time zone default NOW(),
	end_time timestamp with time zone default (NOW() + INTERVAL '7 days')
);

create table Projects (
	id integer generated by default as identity primary key,
	name varchar(150),
	description text);

create table Tasks (
	id integer generated by default as identity primary key,
	developer_id integer references Users(id) on delete set null on update cascade,
	manager_id integer references Users(id) on delete set null on update cascade,
	project_id integer references Projects(id) on delete cascade on update cascade,
	sprint_id integer references Sprints(id) on delete cascade on update cascade,
	title varchar(150),
	note text,
	status task_state default 'Новая',
	created timestamp with TIME zone default NOW(),
	rush bool default false,
	leed int
);

create table Files (
	id integer generated by default as identity primary key,
	task_id integer references Tasks(id) on delete cascade on update cascade,
	name varchar(200),
	size int default 0,
	link varchar(1024)
);

create table Notes (
	id integer generated by default as identity primary key,
	user_id integer references Users(id) on delete cascade on update cascade,
	task_id integer references Tasks(id) on delete cascade on update cascade,
	note text,
	created timestamp with time zone default NOW()
);
 
create table Logs (
	id integer generated by default as identity primary key,
	user_id integer references Users(id) on delete cascade on update cascade,
	task_id integer references Tasks(id) on delete cascade on update cascade,
	time timestamp with time zone default NOW(),
	value JSON
);

insert into users (login,passwd,name,role) values ('Админ','1','Администратор Иван','Админ');
insert into users (login,passwd,name,role) values ('Max','1','Максим Прохоров','Разработчик');
insert into users (login,passwd,name,role) values ('Den','1','Денис Сидоров','Разработчик');
insert into users (login,passwd,name,role) values ('Sid','1','Сидор Иванов','Разработчик');
insert into users (login,passwd,name,role) values ('Sidr','1','Менеджер Сидоров','Менеджер');
insert into users (login,passwd,name,role) values ('Petr','1','Менеджер Петров','Менеджер');

insert into projects (name,description) values ('Проект 1','Очень серьезныйПроект');
insert into projects (name,description) values ('Проект 2','Второй, не менее серьезный Проект');
insert into projects (name,description) values ('Проект 3','Самый серьезный Проект');

insert into sprints (name) values ('Спринт 1');
insert into sprints (name) values ('Спринт 2');
insert into sprints (name) values ('Спринт 3');

insert into tasks (developer_id,manager_id,project_id,sprint_id,title,note,leed) values (2,3,2,1,'Товары','Прикрепение товара\nк новости',10);
insert into tasks (developer_id,manager_id,project_id,sprint_id,title,note,leed) values 
		(2,3,2,1,'Админка','В создании/редактировании отзыва\nневозможно пересохранить\nпривязку к отзыву\nо товаре',20);

insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (2, 6, 3, 3, 'Монетизация действенных систем', 'Ассимилированная и масштабируемая конгломерация', 'Отменена', '2025-09-12 10:38:36', False,19);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (3, 5, 2, 2, 'Координация притягательных взаимодействий', 'Разнообразное и прибыльное ядро', 'Ревью', '2025-08-30 16:40:24', False,18);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (4, 5, 2, 1, 'Охват кроссплатформенных интернет-компаний', 'Автономное и инструктивное межплатформенное программное обеспечение', 'Новая', '2025-09-06 21:50:39', False,15);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (3, 5, 3, 2, 'Переход притягательных сообществ', 'Синхронизированная и систематическая парадигма', 'Новая', '2025-09-04 03:03:41', False,17);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (4, 6, 2, 2, 'Сравнение фронт-энд интернет-продавцов', 'Централизованная и масштабируемая миграция', 'Выливка', '2025-09-03 15:30:46', False,16);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (3, 5, 3, 1, 'Революция наглядных парадигм', 'Взаимовыгодный и переходный фреймворк', 'Новая', '2025-09-04 00:08:59', False,16);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (2, 5, 1, 3, 'Оптимизация критически важных интернет-продавцов', 'Межгрупповой и энергонезависимый графический интерфейс', 'Новая', '2025-09-17 19:50:48', False,12);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (4, 5, 3, 3, 'Мотивация стратегических платформ', 'Управляемая и максимальная реализация', 'Возвращена', '2025-09-04 07:30:11', False,15);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (2, 6, 2, 1, 'Разработка беспроводных интернет-продавцов', 'Устойчивая и локальная инфраструктура', 'Проверена', '2025-09-03 10:39:59', False,17);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (2, 5, 2, 1, 'Продление притягательных интернет-компаний', 'Увеличенный и потенциальный адаптер', 'Готова к работе', '2025-09-19 09:41:38', False,18);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (3, 6, 3, 1, 'Мотивация целостных функций', 'Многослойная и бездефектная структура', 'Выливка', '2025-09-08 13:33:13', False,13);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (3, 6, 2, 3, 'Мотивация B2C партнерств', 'Корпоративная и заметная иерархия', 'В работе', '2025-09-15 17:13:54', False,11);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (2, 6, 1, 2, 'Продление лучших в своём роде результатов', 'Расширенное и региональное программное обеспечение', 'Готова к работе', '2025-09-16 22:10:46', False,18);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (4, 6, 3, 2, 'Обеспечение революционных инициатив', 'Дублируемое и нестандартное приложение', 'Выливка', '2025-08-29 21:54:54', False,17);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (3, 6, 1, 3, 'Переход инновационных ниш', 'Бизнес-ориентированная и мобильная сеть Экстранет', 'Готова к работе', '2025-09-10 07:02:37', False,15);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (3, 5, 3, 1, 'Сравнение ультрасовременных архитектур', 'Реконструируемая и национальная миграция', 'На обсуждении', '2025-08-25 17:21:38', False,12);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (2, 5, 2, 2, 'Производство целостных областей интереса', 'Эргономичное и вторичное совершенствование процесса', 'Новая', '2025-09-03 11:46:12', False,19);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (2, 6, 2, 1, 'Обеспечение круглогодичных систем', 'Продвинутая и круглосуточная база знаний', 'На обсуждении', '2025-09-04 10:55:05', False,14);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (2, 6, 2, 2, 'Развитие фронт-энд инициатив', 'Многоканальная и двунаправленная политика', 'Выполнена', '2025-09-10 06:21:15', False,10);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (3, 6, 1, 2, 'Координация критически важных взаимодействий', 'Универсальный и двунаправленный альянс', 'На обсуждении', '2025-09-16 23:52:28', False,13);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (3, 5, 3, 2, 'Приспособление масштабируемых интерфейсов', 'Объектный и яркий массив', 'Отменена', '2025-09-01 03:47:03', False,17);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (3, 6, 1, 1, 'Перезагрузка богатых инфопосредников', 'Устойчивое и заметное оборудование', 'Новая', '2025-08-29 00:18:58', False,9);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (3, 5, 3, 2, 'Включение притягательных ниш', 'Централизованная и бездефектная поддержка', 'В работе', '2025-09-16 22:39:22', False,16);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (4, 5, 2, 2, 'Обеспечение беспроводных каналов', 'Ориентированное и ультрасовременное управление бюджетом', 'В работе', '2025-09-17 11:10:56', False,18);
insert into tasks (developer_id, manager_id, project_id, sprint_id,title, note, status, created, rush, leed)  values (4, 5, 1, 3, 'Конструирование передовых каналов', 'Универсальный и промежуточный интерфейс', 'Готова к работе', '2025-08-25 08:56:01', False,11);
